
name: build-wheels

on:
  pull_request:
  push:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: st235/opencv_tflite
      volumes:
        - ${{ github.workspace }}:/project
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build wheel asnd install
      run: |
        python -m pip install --user --upgrade build
        python -m build
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          dist
