
name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
          python-version: 3.9
    - name: Install dependencies (prod + dev)
      run: |
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files
