
name: verify-code

on:
  pull_request:
  push:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: st235/opencv_tflite
      volumes:
        - ${{ github.workspace }}:/project
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install -r dev-requirements.txt
    - name: Run lint
      run: |
        pylint .
    - name: Run tests
      run: |
        pytest .
